# Generated by Django 3.2.8 on 2021-10-28 18:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClassSize_1',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('school_title', models.CharField(max_length=10)),
                ('course_id', models.CharField(max_length=50)),
                ('offer_with', models.CharField(max_length=150)),
                ('section', models.PositiveIntegerField()),
                ('credit_hour', models.PositiveIntegerField()),
                ('room_capacity', models.PositiveIntegerField()),
                ('enrolled', models.PositiveIntegerField()),
                ('freespace', models.IntegerField()),
                ('room_id', models.CharField(max_length=50)),
                ('blocked', models.BooleanField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('st_mw', models.CharField(max_length=5)),
                ('year', models.CharField(max_length=5)),
                ('semester', models.CharField(max_length=10)),
            ],
        ),
    ]
