# Generated by Django 3.2.8 on 2021-10-28 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Revenue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=5)),
                ('semester_num', models.PositiveIntegerField()),
                ('SBE', models.PositiveBigIntegerField(null=True)),
                ('SETS', models.PositiveBigIntegerField(null=True)),
                ('SELS', models.PositiveBigIntegerField(null=True)),
                ('SLASS', models.PositiveBigIntegerField(null=True)),
                ('SPPH', models.PositiveBigIntegerField(null=True)),
                ('total', models.PositiveBigIntegerField(null=True)),
            ],
        ),
    ]
